"""
STEP 0: get price bars.

Two sources:
  * load_mt5_csv()  - your own history exported from MetaTrader 5
  * simulate()      - a Volatility-75-style random walk, with or without a planted edge

Every function returns a DataFrame indexed by time with columns open, high, low, close.
"""
import numpy as np
import pandas as pd


# ---------------------------------------------------------------------------- MT5 CSV
def load_mt5_csv(path):
    """Read a CSV exported from MT5 (View > Symbols > Bars > Export, or a script).

    Works with MT5's own format (<DATE> <TIME> <OPEN> <HIGH> <LOW> <CLOSE> ...)
    and with a plain "time,open,high,low,close" file.
    """
    with open(path, "rb") as fh:
        start = fh.read(4)
    enc = "utf-16" if start[:2] in (b"\xff\xfe", b"\xfe\xff") or b"\x00" in start else "utf-8-sig"
    df = pd.read_csv(path, sep=None, engine="python", encoding=enc)
    df.columns = [str(c).strip().strip("<>").lower() for c in df.columns]

    if "date" in df.columns and "time" in df.columns:
        raw = df["date"].astype(str) + " " + df["time"].astype(str)
    else:
        tcol = next(c for c in ("time", "datetime", "timestamp", "date") if c in df.columns)
        raw = df[tcol].astype(str)

    ts = None
    for fmt in ("%Y.%m.%d %H:%M:%S", "%Y.%m.%d %H:%M", "%Y-%m-%d %H:%M:%S", "%Y-%m-%d %H:%M"):
        try:
            ts = pd.to_datetime(raw, format=fmt)
            break
        except (ValueError, TypeError):
            continue
    if ts is None:
        ts = pd.to_datetime(raw)

    out = pd.DataFrame(
        {c: df[c].astype(float).to_numpy() for c in ("open", "high", "low", "close")},
        index=pd.DatetimeIndex(ts, name="time"),
    )
    if "spread" in df.columns:
        out["spread_points"] = df["spread"].astype(float).to_numpy()
    out = out[~out.index.duplicated(keep="first")].sort_index()
    return out


# ---------------------------------------------------------------------------- simulator
def simulate(n_bars=60_000, mode="random", seed=7, bar_minutes=15, annual_vol=0.75,
             substeps=150, start_price=500_000.0):
    """Volatility-75-style prices: a random walk with constant volatility, 24/7.

    Deriv describes its volatility indices as generated by "a cryptographically secure
    random process" with "fixed and known volatility". That is what mode="random" builds.
    In such a market no entry rule can beat about 1/(target_R + 1) wins at target_R.

    mode="planted" adds a hidden pattern: sweep -> displacement -> pullback, which runs
    20R+ when it happens in the morning (07:00-11:00 UTC) and is a trap that stops you
    out in the afternoon (13:00-17:00 UTC). This is a known, real edge, so a working
    pipeline must find it. (Real markets are never this clean. It is a test, not a promise.)
    """
    rng = np.random.default_rng(seed)
    seconds_per_year = 365 * 24 * 3600
    ticks_per_bar = bar_minutes * 60 / 2                         # one tick every 2 seconds
    sigma_tick = annual_vol * np.sqrt(2 / seconds_per_year)
    sigma_sub = sigma_tick * np.sqrt(ticks_per_bar / substeps)   # each substep = several ticks
    sigma_bar = sigma_sub * np.sqrt(substeps)

    inc = rng.normal(-0.5 * sigma_sub ** 2, sigma_sub, size=(n_bars, substeps))
    index = pd.date_range("2024-01-01", periods=n_bars, freq=f"{bar_minutes}min", name="time")

    episodes = []
    if mode == "planted":
        episodes = _plant_edge(inc, index, sigma_bar, rng)
    elif mode != "random":
        raise ValueError("mode must be 'random' or 'planted'")

    logp = np.log(start_price) + np.cumsum(inc.ravel()).reshape(n_bars, substeps)
    close = logp[:, -1]
    open_ = np.r_[np.log(start_price), close[:-1]]
    high = np.maximum(open_, logp.max(axis=1))
    low = np.minimum(open_, logp.min(axis=1))
    df = pd.DataFrame({"open": np.exp(open_), "high": np.exp(high),
                       "low": np.exp(low), "close": np.exp(close)}, index=index)
    df.attrs["planted_episodes"] = episodes   # (start bar, direction, kind) - only for checking
    return df


def _plant_edge(inc, index, sigma_bar, rng):
    """Adds two kinds of episodes that look IDENTICAL at the moment of entry:

      real (07:00-11:00 UTC): sweep -> displacement -> pullback -> steady run (20R+ often)
      trap (13:00-17:00 UTC): sweep -> displacement -> pullback -> sharp drop through the stop

    Only the time of day tells them apart. So taking every setup is mediocre, but a
    model that learns "morning setups work, afternoon ones are traps" does very well.
    That is the kind of thing the model is supposed to find in your data.
    """
    n_bars, substeps = inc.shape
    a = 1.6 * sigma_bar                  # roughly one ATR in log-price terms
    hours = index.hour.to_numpy()
    common = ([-1.3] * 3 +               # sweep: push below the recent lows
              [+4.0, +2.5] +             # displacement: big candles the other way
              [-1.3] * 4)                # pullback into the order block
    shapes = {"real": np.array(common + [+0.30] * 120) * a,   # the run
              "trap": np.array(common + [-1.4] * 3) * a}      # through the stop, then nothing
    episodes = []
    t = 600
    longest = max(len(v) for v in shapes.values())
    while t < n_bars - longest - 1:
        kind = "real" if 7 <= hours[t] < 11 else "trap" if 13 <= hours[t] < 17 else None
        if kind and rng.random() < 0.15:
            shape = shapes[kind]
            direction = 1 if rng.random() < 0.5 else -1
            inc[t:t + len(shape)] += (direction * shape / substeps)[:, None]
            episodes.append((t, direction, kind))
            t += len(shape) + int(rng.integers(30, 150))
        else:
            t += 1
    return episodes
